name: unit-tests
on:
  # Trigger the workflow on push or pull request,
  # but only for the main/develop branch
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: python-{{ cookiecutter.version }}
      uses: actions/setup-python@v2
      with:
        python-version: {{ cookiecutter.version }}
    - name: install-dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -e .
    - name: flake8
      run: |
        config/hooks/pre-commit
    - name: print env
      run: |
        env
    - name: pytest
      run: |
        pytest
    - name: end2end-toyexp
      run: |
        cd examples/local
        sh run.sh
